name: Connect to an AWS role from a GitHub repository 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: Setup Terraform
    runs-on: ubuntu-latest
    outputs:
      terraform_version: ${{ steps.set_tf_version.outputs.version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        id: set_tf_version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

  configure-aws:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    outputs:
      aws_credentials: ${{ steps.aws_setup.outputs.aws_creds }}
    steps:
      - name: Configure AWS credentials
        id: aws_setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          role-session-name: GitHub_to_AWS
          aws-region: ${{ env.AWS_REGION }}
  
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [ setup, configure-aws ]
    steps:
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ needs.setup.outputs.terraform_version }}

      - name: List repository files
        run: ls -R

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply