name: Connect to an AWS role from a GitHub repository 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env: 
  AWS_REGION: "eu-central-1"

jobs:
  terraform-plan:
    defaults:
      run:
        working-directory: ./terraform
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: aws_setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          role-session-name: GitHub_to_AWS
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        id: set_tf_version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply