replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

storage:
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClassName: manual

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
